title: "My Network Tools / Other Stuff Blog"
repository: Robert_kuhn/network_tools_blog
description: "My personal blog on programming, life, lessons learned and the like."
url: "https://google.com"
baseurl: ""  # for user/organization pages; set to "/repo-name" for project pages

author:
  name: "Robert Kuhn"
  email: "robertkuhn4512@gmail.com"

# GitHub Pages will auto-enable safe plugins; we keep it simple.
markdown: kramdown
highlighter: rouge

# Permalinks for posts
permalink: /blog/:year/:month/:day/:title/

# Exclude stuff that shouldn't be processed
exclude:
  - README.md
  - node_modules
  - vendor